server:
  min_threads: 1
  max_threads: 32
  workers: 8
  ports:
    - 9000
    - 3000
  demonize: false
synchronizer:
  api_key: g72HTAiD7ysCjtBxgRpf
  protocol: https
  hostname: destinationbook-testing.herokuapp.com
  uri:
    trips: export/trips
    wallet: export
